function [hY] = fcnPlotKc(ax,chi_P,datTel01,datTel1,datTel5,datTel10,YLim)
% ax;
% hold on;
x = chi_P;

hY = semilogy(ax,...
    x,datTel01(1,:),'r-',...
    x,datTel01(2,:),'r--',...
    x,datTel1(1,:),'g-',...
    x,datTel1(2,:),'g--',...
    x,datTel5(1,:),'b-',...
    x,datTel5(2,:),'b--',...
    x,datTel10(1,:),'k-',...
    x,datTel10(2,:),'k--');
    
ylim(ax,YLim);
grid(ax,'on')
set(findall(ax,'type','line'),'linewidth',1);


